### ISSUE TITLE
pyhc-requirements.txt contains PyHC packages

### ISSUE THREAD

**Issue by xandrd** [sapols/pyhc-environment-files#2]
@sapols I just realized that aacgmv2 is a PyHC package. It is technically outside of the python bare environment for PyHC packages. But it is included in [pyhc-requirements.txt](https://github.com/sapols/pyhc-environment-files/blob/main/pyhc-requirements.txt), same as plasmapy.

I think, we should clean [pyhc-requirements.txt](https://github.com/sapols/pyhc-environment-files/blob/main/pyhc-requirements.txt). Does [pyhc-packages-requirements.txt](https://github.com/sapols/pyhc-environment-files/blob/main/pyhc-packages-requirements.txt) have all PyHC packages?

**Comment by xandrd** [comment]
I've added [cross-reference-check.py](https://github.com/sapols/pyhc-environment-files/blob/overlap/cross-reference-check.py) script into `overlap` branch that shows overlaped packages between "bare" and "pyhc" packages requirements files.
And here they are:
```
{'sciencedates', 'ndcube', 'viresclient', 'cdflib', 'aacgmv2', 'pytplot-mpl-temp', 'plasmapy', 'hapiclient', 'msise00', 'sunpy', 'sunraster', 'pysat'}
```

**Comment by sapols** [comment]
Thanks for this @xandrd! I've updated `pyhc-requirements.txt` on the main branch.
